### ISSUE TITLE
Updating posts

### ISSUE THREAD

**Issue by hellomrdavis** [morgancurrie/marcato_festival_wordpress_plugin#7]
Quick question. Is this strictly to import data? If updates are made or additional custom fields are created in Marcato will they not reflect within Wordpress?

**Comment by Adamlb** [comment]
Not sure if you are still looking for this answer, but the plugin sets up a Wordpress cron-job that will retrieve updates from Marcato every hour, this can be turned off or done manually at any time from the Marcato settings screen but clicking import again.
