### ISSUE TITLE
Question: Script times out and never finishes importing. Work around?

### ISSUE THREAD

**Issue by Acct3d** [morgancurrie/marcato_festival_wordpress_plugin#9]
Hosting has a maximum execution time set to 30. Script times out and no matter how many times I retry it continues to time out and doesn't imports newer entries.

**Comment by Adamlb** [comment]
I have mostly only ever got execution timeouts when including images from marcato as featured images, especially if there are a lot of them.

The plugin downloads the images from marcato and this can take a while, however it will only download images if they have changed, this is why retrying a few times usually works. I'm afraid if you can't increase the execution time, and you are wishing to include images, there isn't really a way around it currently.

If you are not including images and are still getting timeouts, you can contact support@marcatodigital.com
